### ISSUE TITLE
未连接钱包状态下，不能注册，红框内按钮改为Connect Wallet，点击跳出连接钱包弹窗

### ISSUE THREAD

**Issue by FamelessLeo** [FamelessLeo/Neo-Name-Service#1]
<img width="1361" alt="Screen Shot 2022-04-14 at 5 16 36 PM" src="https://user-images.githubusercontent.com/87798080/163354340-24485e3b-19fe-4377-a777-48fddd7bfaad.png">

**Comment by ShaySong99** [comment]
fixed

**Comment by cloud8little** [comment]
![067154cb9ad413572d891b868fa4633](https://user-images.githubusercontent.com/34291844/164646547-6a02d399-36e0-4951-800f-d0c924452a20.png)
