### ISSUE TITLE
增加一条新记录，交易对所有曾有的记录均调用了一遍

### ISSUE THREAD

**Issue by cloud8little** [FamelessLeo/Neo-Name-Service#10]
https://testnet.explorer.onegate.space/transactionInfo/0x3b957712a9633c1816448c84650c304f606eb5a9b31549dd5c164f6b6c27126c

添加一条新纪录，增加子域名的记录

![de17cfcfcf46afaa36da7fd6951654f](https://user-images.githubusercontent.com/34291844/167060131-fbf00bb2-8a97-4dd4-b1a3-36e86fafd378.png)

**Comment by ShaySong99** [comment]
fix 更新增加前后记录diff，只增加修改过记录

**Comment by cloud8little** [comment]
已验证 https://testnet.explorer.onegate.space/transactionInfo/0xdfadbd3082913ed68e6edaaa8b9c3b44523e362d7e8f715ffb13b9a614a24a16
