### ISSUE TITLE
设置管理员为当前域名拥有者地址，应该直接发送交易上链

### ISSUE THREAD

**Issue by cloud8little** [FamelessLeo/Neo-Name-Service#11]
![1c943f883c88a4ea2087ec0ccf37142](https://user-images.githubusercontent.com/34291844/167063878-eb1f9d38-51a5-4b81-a464-fb1bbfd15194.png)

![eeac50502cafcace65c304adbd61a45](https://user-images.githubusercontent.com/34291844/167063771-0e3a85b9-18d2-4be9-aa16-da03d2ab01f2.png)

**Comment by ShaySong99** [comment]
fix 
在第一个框输入的地址如果是注册人的，就出现一个弹窗提醒“你已经是注册者了，请填写其他地址。

**Comment by cloud8little** [comment]
![788f68f9a203f6d0b84a0fa347f4a32](https://user-images.githubusercontent.com/34291844/168539031-e6570151-7f86-45ec-952b-de57e5d719b2.png)
