### ISSUE TITLE
添加TXT记录时，长度超过256直接报错

### ISSUE THREAD

**Issue by cloud8little** [FamelessLeo/Neo-Name-Service#12]
![b7022b77a752acd227fe17e4b5d6dcc](https://user-images.githubusercontent.com/34291844/168516388-7010d3b2-bdf2-4784-8ac6-2a63cb0c83dc.png)

**Comment by ShaySong99** [comment]
fix

**Comment by cloud8little** [comment]
包含特殊字符的没检查
`十一*&（）() fe-+=☎☏✄☪☣☢☠♨« »큐〓㊚㊛囍㊒㊖☑✔☐☒✘㍿☯☰☷♥♠♤ ♂♀★☆☯✡※🦸hero~~~~~~~-+=☎☏✄☪☣☢☠♨« »큐 〓㊚㊛囍㊒㊖㊒㊖☑✔☐☒✘㍿☯☰☷♥♠♤ ♂♀★☆☯fe-+=☎☏✄☪☣☢☠♨« »큐〓㊚㊛囍`

![image](https://user-images.githubusercontent.com/34291844/170217088-d5723129-ee8b-455c-b431-a897f96b7ef4.png)

**Comment by ShaySong99** [comment]
fix 改为判断字符串字节长度

**Comment by cloud8little** [comment]
已验证 

![7d1107e52e20230921c4279003870d9](https://user-images.githubusercontent.com/34291844/170454867-d8e1b441-6e0c-407b-8048-8d7b75b6b8d6.png)
