### ISSUE TITLE
点击在浏览器中查看没有具体交易信息

### ISSUE THREAD

**Issue by cloud8little** [FamelessLeo/Neo-Name-Service#3]
![f4660465f5e9d2af826f936a41e60a9](https://user-images.githubusercontent.com/34291844/163540952-727f3553-c285-4ff7-9c7e-4ba33ffdc3f7.png)

链接转向 [testnet.explorer.onegate.space](https://testnet.explorer.onegate.space/homepage)

**Comment by ShaySong99** [comment]
已处理
