### ISSUE TITLE
点击续费年限，”续费至“显示仍然为当前过期时间

### ISSUE THREAD

**Issue by cloud8little** [FamelessLeo/Neo-Name-Service#4]
![0d0e99f696530f10f807ed9758e73cd](https://user-images.githubusercontent.com/34291844/163542195-94e4d7a0-792a-40ee-b332-fab633129432.png)

**Comment by ShaySong99** [comment]
已处理

**Comment by cloud8little** [comment]
![7d87936afeb7c7fe3d61e43cb9432db](https://user-images.githubusercontent.com/34291844/164646302-2543b5c0-a506-4bad-a711-de8441b10db3.png)
