### ISSUE TITLE
添加新纪录时，如果遇到类型和Host相同的情况，不允许添加

### ISSUE THREAD

**Issue by cloud8little** [FamelessLeo/Neo-Name-Service#5]
前端需要限制一下，只能在原有已存在的记录中进行修改

![3e78388e758a01d8c335afcb7ff8c76](https://user-images.githubusercontent.com/34291844/163542451-6d311194-5aa0-4844-8c57-fe60a973643f.png)

**Comment by ShaySong99** [comment]
已处理
