### ISSUE TITLE
到期时间 显示

### ISSUE THREAD

**Issue by cloud8little** [FamelessLeo/Neo-Name-Service#6]
域名： april.neo
查看properties 显示到期时间： 1713003598543  毫秒换算： 2024-04-13 18:19:58

![9762d1946b2ce1c2e7bf22c584085e6](https://user-images.githubusercontent.com/34291844/163547925-d0167e24-9d53-4fa0-950b-58c0794ed7d2.png)

**Comment by ShaySong99** [comment]
已处理

**Comment by cloud8little** [comment]
![d638b716ef68824cd8d84717ae3b27a](https://user-images.githubusercontent.com/34291844/164645899-be118bfa-9f92-4973-8380-3d444b140567.png)
